### ISSUE TITLE
中文繁简转换的配置文件t2s.json

### ISSUE THREAD

**Issue by renmengjie7** [HIT-SCIR/plm-nlp-code#11]
请问第三章中文繁简转换的配置文件t2s.json上传了嘛？（在书的64页）GitHub上我没找着

**Comment by ymcui** [comment]
{
  "name": "Traditional Chinese to Simplified Chinese",
  "segmentation": {
    "type": "mmseg",
    "dict": {
      "type": "ocd2",
      "file": "TSPhrases.ocd2"
    }
  },
  "conversion_chain": [{
    "dict": {
      "type": "group",
      "dicts": [{
        "type": "ocd2",
        "file": "TSPhrases.ocd2"
      }, {
        "type": "ocd2",
        "file": "TSCharacters.ocd2"
      }]
    }
  }]
}

**Comment by ymcui** [comment]
https://github.com/HIT-SCIR/plm-nlp-code/blob/main/chp3/t2s.json
